#ifndef _DEFINES_H
#define _DEFINES_H

#define MAX_NUMBERS_DIGITS 20

#define MAX_BASH_COMMAND 2000

#define MAX_ADDRESS_LENGTH 1000

#define MAX_COMMAND_LENGTH 1000
#define MAX_NUMBER_OF_COMMNAD 10

#define MAX_LINE_IN_FILES_LENGTH 1000

#define MAX_USERNAME_LENGTH 100
#define MAX_USEREMAIL_LENGTH 500

#define MAX_COMMIT_MESSAGE_LENGTH 72

#define MAX_PERMISSIONS_LENGTH 20

#define MAX_BRANCH_NAME_LENGTH 100

#define MAX_TAG_NAME_LENGTH 100
#define MAX_TAG_MESSAGE_LENGTH 100
#define MAX_NUMBER_OF_TAGS 20

#define NEOGIT_GLOBAL_ADDRESS "/home/soheil/Drive_D/Soheil/Study/University/CE/FOP/Project/neogit/.neogit-global/"

#endif