#ifndef _DEFINES_H
#define _DEFINES_H

#define MAX_NUMBERS_DIGITS 20

#define MAX_BASH_COMMAND 2000

#define MAX_ADDRESS_LENGHT 1000

#define MAX_COMMAND_LENGHT 1000
#define MAX_NUMBER_OF_COMMNAD 10

#define MAX_LINE_IN_FILES_LENGTH 1000

#define MAX_USERNAME_LENGHT 100
#define MAX_USEREMAIL_LENGTH 500

#define MAX_COMMIT_MESSAGE_LENGHT 72

#define MAX_BRANCH_NAME_LENGHT 100

#define NEOGIT_GLOBAL_ADDRESS "/home/soheil/Drive_D/Soheil/Study/University/CE/FOP/Project/neogit/.neogit-global/"

#endif